import {Panel,C,type FigureSpec} from '@llm-systems/viz';
export default {
 articleId:'rl-10',figureId:'02-training-and-deployment',number:'10-2',eyebrow:['그림 2','Figure 2'],captionIn:'article',
 title:['학습 스텝과 배포 버전은 다른 속도로 증가한다','Training steps and rollout versions advance separately'],
 subtitle:['교육용 예: 스텝마다 한 번 업데이트하고, 세 스텝마다 가중치를 반영합니다.','Illustrative example: one update per step; synchronize weights every three steps.'],
 alt:['학습은 step 9에서 12까지 진행한다. 추론기는 step 9의 가중치인 v3을 사용하다 step 12에서 sync한 뒤 v4가 된다. step 11에서는 학습이 두 번 진행됐지만 v3 데이터의 배포 버전 간격은 0이다.','Training advances from step 9 to 12. Inference keeps v3 from step 9 until synchronization at step 12 publishes v4. At step 11, v3 data has rollout-version lag zero despite two learner updates.'],caption:['',''],
 sources:[{label:'Miles fully async',url:'https://github.com/radixark/miles/blob/main/docs/user-guide/fully-async.md'}],
 panels(locale){
 const p=new Panel(locale,['두 개의 진행 기록','Two progress counters'],650);
 p.text(20,121,['학습기','Learner'],{size:22,weight:600,color:C.teal});p.text(315,121,['추론기','Inference'],{size:22,weight:600,color:C.blue});
 const ys=[153,271,389,507];
 ys.forEach((y,i)=>{p.box(16,y,206,76,`step ${9+i}`,'','teal');if(i<3)p.arrow(119,y+81,119,y+111,C.teal);});
 p.box(300,153,204,312,'v3',['step 9 가중치','Step 9 weights'],'blue');
 p.box(300,507,204,76,'v4','','blue');
 p.arrow(228,189,294,189,C.orange);p.text(260,170,'sync',{size:17,anchor:'middle',color:C.orange});
 p.arrow(228,543,294,543,C.orange);p.text(260,524,'sync',{size:17,anchor:'middle',color:C.orange});
 p.text(16,626,['step 10·11: 추론 가중치 유지','Steps 10–11: inference weights unchanged'],{size:21,width:488,color:C.muted});
 const q=new Panel(locale,['step 11에서 확인하기','At step 11'],650);
 q.box(16,110,488,105,['학습기: step 11','Learner: step 11'],['v3 반영 이후 두 번 업데이트','Two updates since publishing v3'],'teal');
 q.box(16,237,488,105,['추론기: 마지막 배포 v3','Inference: last published v3'],['아직 다음 sync 전','Before the next synchronization'],'blue');
 q.arrow(260,349,260,387,C.blue);
 q.box(16,397,488,105,['v3으로 만든 경험','Experience generated by v3'],['현재 배포 v3 − 생성 v3 = 0','Current rollout v3 − generation v3 = 0'],'purple');
 q.text(24,553,['배포 버전 간격 0','Rollout-version lag: 0'],{size:25,weight:600,width:470,color:C.purple});
 q.text(24,602,['학습기와 가중치가 같다는 뜻은 아님','Learner weights can still differ'],{size:22,width:470,color:C.muted});
 return [p,q];}
} satisfies FigureSpec;
