import {Panel,C,type FigureSpec,type Locale} from '@llm-systems/viz';
export default {
  articleId:'rl-04',figureId:'01-student-visited-contexts',number:'4-1',
  captionIn:'article',
  eyebrow:['그림 1','Figure 1'],
  title:['학생이 방문한 문맥에서 교사의 확률을 읽는다','Read teacher probabilities on contexts visited by the student'],
  subtitle:['SFT는 주어진 답의 경로를 따릅니다. OPD는 학생이 만든 경로 위에서 교사의 학습 신호를 구합니다.','SFT follows a provided answer. OPD obtains teacher signals along a path generated by the student.'],
  alt:['같은 질문P에서 SFT의 주어진답은 u,a,c이고 학생이 생성한 OPD경로는 u,b,d이다. SFT는 P,Pu,Pua 문맥에서 주어진 다음토큰을 목표로 삼고 OPD는 P,Pu,Pub 문맥에서 학생 선택 u,b,d의 교사확률을 구한다.','For prompt P, the SFT answer is u,a,c while the student generates u,b,d. SFT targets the given next token in contexts P,Pu,Pua. OPD evaluates teacher probabilities for the student choices u,b,d in contexts P,Pu,Pub.'],
  caption:['u·a·b·c·d는 설명용 토큰입니다. 화살표는 논리적 평가 관계이며, 교사 평가는 완성된 학생 경로를 묶어 순전파로 처리할 수 있습니다.','u, a, b, c and d are illustrative tokens. Arrows show logical evaluations; teacher scoring can process a completed student trajectory in a batched forward pass.'],
  sources:[{label:'Thinking Machines — On-policy distillation',url:'https://thinkingmachines.ai/blog/on-policy-distillation/'}],
  panels(locale:Locale){return [false,true].map(opd=>{
    const p=new Panel(locale,opd?['OPD: 학생이 경로를 생성','OPD: the student makes the path']:['SFT: 주어진 답의 경로','SFT: a provided answer’s path'],837);
    p.box(16,100,488,84,['같은 질문 P','The same prompt P'],'','gray');
    const toks=opd?['u','b','d']:['u','a','c'];
    toks.forEach((t,i)=>{p.token(26+i*176,216,t,112,i===0?'gray':opd?'blue':'orange');if(i<2)p.arrow(150+i*176,240,187+i*176,240,opd?C.blue:C.orange);});
    p.text(16,308,opd?['학생의 실제 문맥','Student prefix']:['주어진 답의 문맥','Provided-answer prefix'],{size:21,width:256,weight:600});
    p.text(304,308,opd?['교사의 확률','Teacher p']:['목표 토큰','Target token'],{size:21,width:200,weight:600,color:opd?C.purple:C.orange});
    const ctx=['P','P + u',`P + u + ${toks[1]}`];
    ctx.forEach((s,i)=>{
      const y=342+i*132;
      p.box(16,y,242,104,s,['행동 직전 문맥','Input prefix'],'gray');
      p.arrow(269,y+50,291,y+50,opd?C.purple:C.orange);
      p.box(304,y,200,104,opd?`pT(${toks[i]})`:toks[i],opd?['이 문맥에서','In this context']:['주어진 다음 토큰','Given next token'],opd?'purple':'orange');
    });
    p.text(16,762,opd?['교사는 학생의 선택을 평가합니다.','The teacher evaluates the student’s choices.']:['답의 출처가 반드시 교사일 필요는 없습니다.','The provided answer need not come from a teacher.'],{size:21,width:488,color:C.muted});
    return p;
  });},
} satisfies FigureSpec;
